### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by hmedat** [tuenti/SmsRadar#14]
Hello Guys 

I got this crash from Fabric 

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.ContentResolver.unregisterContentObserver(android.database.ContentObserver)' on a null object reference
       at com.tuenti.smsradar.SmsRadarService.unregisterSmsContentObserver(SmsRadarService.java:126)
       at com.tuenti.smsradar.SmsRadarService.finishService(SmsRadarService.java:115)
       at com.tuenti.smsradar.SmsRadarService.onDestroy(SmsRadarService.java:71)
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3504)
       at android.app.ActivityThread.-wrap26(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

<img width="1148" alt="screen shot 2018-07-04 at 10 35 15 am" src="https://user-images.githubusercontent.com/4534097/42263209-03c7f168-7f76-11e8-962c-1f0ceaef7828.png">

**Comment by hmedat** [comment]
?
